# Generated by Django 2.1.7 on 2019-03-28 19:53

from django.db import migrations, models
import django.db.models.deletion
import esite.home.models
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_title', models.CharField(max_length=255)),
                ('button_id', models.CharField(blank=True, max_length=255)),
                ('button_class', models.CharField(blank=True, max_length=255)),
                ('button_link', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.CharField(blank=True, help_text='Default value. Comma separated values supported for checkboxes.', max_length=255, verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('thank_you_text', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='UniquePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('city', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('telefax', models.CharField(blank=True, max_length=255)),
                ('vat_number', models.CharField(blank=True, max_length=255)),
                ('tax_id', models.CharField(blank=True, max_length=255)),
                ('court_of_registry', models.CharField(blank=True, max_length=255)),
                ('place_of_registry', models.CharField(blank=True, max_length=255)),
                ('trade_register_number', models.CharField(blank=True, max_length=255)),
                ('ownership', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('copyrightholder', models.CharField(max_length=255)),
                ('privacy', wagtail.core.fields.RichTextField(blank=True)),
                ('sociallinks', wagtail.core.fields.StreamField([('sociallink', wagtail.core.blocks.StructBlock([('icon', wagtail.core.blocks.CharBlock(classname='full')), ('link', wagtail.core.blocks.CharBlock(classname='full'))], icon='doc-full'))])),
                ('headers', wagtail.core.fields.StreamField([('h_hero', wagtail.core.blocks.StructBlock([('hero_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('hero_head', wagtail.core.blocks.CharBlock(blank=True, classname='full title')), ('hero_subhead', wagtail.core.blocks.RichTextBlock(blank=True, classname='full', features=['bold', 'italic', 'underline', 'strikethrough', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'hr', 'embed', 'link', 'document-link', 'image'])), ('hero_button', wagtail.snippets.blocks.SnippetChooserBlock(esite.home.models.Button))], icon='image'))])),
                ('sections', wagtail.core.fields.StreamField([('s_why', wagtail.core.blocks.StructBlock([('why_head', wagtail.core.blocks.CharBlock(blank=True, classname='full title')), ('why_collum1', wagtail.core.blocks.StructBlock([('collum_image', wagtail.images.blocks.ImageChooserBlock(classname='full', required=False)), ('collum_paragraph', wagtail.core.blocks.RichTextBlock(blank=True, classname='full', features=['bold', 'italic', 'underline', 'strikethrough', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'hr', 'embed', 'link', 'document-link', 'image']))], icon='cogs')), ('why_collum2', wagtail.core.blocks.StructBlock([('collum_image', wagtail.images.blocks.ImageChooserBlock(classname='full', required=False)), ('collum_paragraph', wagtail.core.blocks.RichTextBlock(blank=True, classname='full', features=['bold', 'italic', 'underline', 'strikethrough', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'hr', 'embed', 'link', 'document-link', 'image']))], icon='cogs')), ('why_collum3', wagtail.core.blocks.StructBlock([('collum_image', wagtail.images.blocks.ImageChooserBlock(classname='full', required=False)), ('collum_paragraph', wagtail.core.blocks.RichTextBlock(blank=True, classname='full', features=['bold', 'italic', 'underline', 'strikethrough', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'hr', 'embed', 'link', 'document-link', 'image']))], icon='cogs')), ('why_button', wagtail.snippets.blocks.SnippetChooserBlock(esite.home.models.Button))], icon='group')), ('s_individual', wagtail.core.blocks.StructBlock([('individual_head', wagtail.core.blocks.CharBlock(blank=True, classname='full title')), ('individual_image', wagtail.images.blocks.ImageChooserBlock(classname='full', required=False)), ('individual_lead', wagtail.core.blocks.RichTextBlock(blank=True, classname='full', features=['bold', 'italic', 'underline', 'strikethrough', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'hr', 'embed', 'link', 'document-link', 'image'])), ('individual_paragraph', wagtail.core.blocks.RichTextBlock(blank=True, classname='full', features=['bold', 'italic', 'underline', 'strikethrough', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'hr', 'embed', 'link', 'document-link', 'image'])), ('individual_button', wagtail.snippets.blocks.SnippetChooserBlock(esite.home.models.Button))], icon='user')), ('s_experts', wagtail.core.blocks.StructBlock([('experts_head', wagtail.core.blocks.CharBlock(blank=True, classname='full title')), ('experts_image', wagtail.images.blocks.ImageChooserBlock(classname='full', required=False)), ('experts_lead', wagtail.core.blocks.RichTextBlock(blank=True, classname='full', features=['bold', 'italic', 'underline', 'strikethrough', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'hr', 'embed', 'link', 'document-link', 'image'])), ('experts_paragraph', wagtail.core.blocks.RichTextBlock(blank=True, classname='full', features=['bold', 'italic', 'underline', 'strikethrough', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'hr', 'embed', 'link', 'document-link', 'image'])), ('experts_button', wagtail.snippets.blocks.SnippetChooserBlock(esite.home.models.Button))], icon='pick')), ('s_lab', wagtail.core.blocks.StructBlock([('lab_head', wagtail.core.blocks.CharBlock(blank=True, classname='full title')), ('lab_image', wagtail.images.blocks.ImageChooserBlock(classname='full', required=False)), ('lab_lead', wagtail.core.blocks.RichTextBlock(blank=True, classname='full', features=['bold', 'italic', 'underline', 'strikethrough', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'hr', 'embed', 'link', 'document-link', 'image'])), ('lab_paragraph', wagtail.core.blocks.RichTextBlock(blank=True, classname='full', features=['bold', 'italic', 'underline', 'strikethrough', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'hr', 'embed', 'link', 'document-link', 'image'])), ('lab_button', wagtail.snippets.blocks.SnippetChooserBlock(esite.home.models.Button))], icon='snippet')), ('s_method', wagtail.core.blocks.StructBlock([('method_head', wagtail.core.blocks.CharBlock(blank=True, classname='full title')), ('method_sphere1', wagtail.core.blocks.StructBlock([('sphere_step', wagtail.core.blocks.RichTextBlock(blank=True, classname='full', features=['bold', 'italic', 'underline', 'strikethrough', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'hr', 'embed', 'link', 'document-link', 'image']))], icon='cogs')), ('method_sphere2', wagtail.core.blocks.StructBlock([('sphere_step', wagtail.core.blocks.RichTextBlock(blank=True, classname='full', features=['bold', 'italic', 'underline', 'strikethrough', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'hr', 'embed', 'link', 'document-link', 'image']))], icon='cogs')), ('method_sphere3', wagtail.core.blocks.StructBlock([('sphere_step', wagtail.core.blocks.RichTextBlock(blank=True, classname='full', features=['bold', 'italic', 'underline', 'strikethrough', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'hr', 'embed', 'link', 'document-link', 'image']))], icon='cogs')), ('method_sphere4', wagtail.core.blocks.StructBlock([('sphere_step', wagtail.core.blocks.RichTextBlock(blank=True, classname='full', features=['bold', 'italic', 'underline', 'strikethrough', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'hr', 'embed', 'link', 'document-link', 'image']))], icon='cogs')), ('method_button', wagtail.snippets.blocks.SnippetChooserBlock(esite.home.models.Button))], icon='site')), ('s_services', wagtail.core.blocks.StructBlock([('services_services', wagtail.core.blocks.StreamBlock([('service', wagtail.core.blocks.StructBlock([('service_head', wagtail.core.blocks.CharBlock(blank=True, classname='full title')), ('service_content', wagtail.core.blocks.RichTextBlock(blank=True, classname='full', features=['bold', 'italic', 'underline', 'strikethrough', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'hr', 'embed', 'link', 'document-link', 'image']))], icon='doc-full'))])), ('services_button', wagtail.snippets.blocks.SnippetChooserBlock(esite.home.models.Button))], icon='openquote')), ('s_reviews', wagtail.core.blocks.StructBlock([('reviews_head', wagtail.core.blocks.CharBlock(blank=True, classname='full title')), ('reviews_reviews', wagtail.core.blocks.StreamBlock([('review', wagtail.core.blocks.StructBlock([('review_image', wagtail.images.blocks.ImageChooserBlock(classname='full', required=False)), ('review_quote', wagtail.core.blocks.RichTextBlock(blank=True, classname='full', features=['bold', 'italic', 'underline', 'strikethrough', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'hr', 'embed', 'link', 'document-link', 'image'])), ('review_name', wagtail.core.blocks.CharBlock(blank=True, classname='full')), ('review_info', wagtail.core.blocks.CharBlock(blank=True, classname='full'))]))]))], icon='form')), ('s_pricing', wagtail.core.blocks.StructBlock([('pricing_head', wagtail.core.blocks.CharBlock(blank=True, classname='full title')), ('pricing_pricingcards', wagtail.core.blocks.StreamBlock([('pricingcard', wagtail.core.blocks.StructBlock([('pricingcard_title', wagtail.core.blocks.CharBlock(blank=True, classname='full title')), ('pricingcard_description', wagtail.core.blocks.RichTextBlock(blank=True, classname='full', features=['bold', 'italic', 'underline', 'strikethrough', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'hr', 'embed', 'link', 'document-link', 'image'])), ('pricingcard_price', wagtail.core.blocks.DecimalBlock(blank=True, decimal_places=2)), ('pricingcard_button', wagtail.snippets.blocks.SnippetChooserBlock(esite.home.models.Button))]))], max_num=3))], icon='home')), ('s_about', wagtail.core.blocks.StructBlock([('about_image', wagtail.images.blocks.ImageChooserBlock(classname='full', required=False)), ('about_head', wagtail.core.blocks.CharBlock(blank=True, classname='full title')), ('about_paragraph', wagtail.core.blocks.RichTextBlock(blank=True, classname='full', features=['bold', 'italic', 'underline', 'strikethrough', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'hr', 'embed', 'link', 'document-link', 'image']))], icon='home'))])),
                ('footers', wagtail.core.fields.StreamField([('f_info', wagtail.core.blocks.StructBlock([('info_placeholder', wagtail.core.blocks.CharBlock(blank=True, classname='full'))], icon='placeholder'))])),
                ('token', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='formfield',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='home.FormPage'),
        ),
    ]
