# Generated by Django 2.1.7 on 2019-04-01 20:14

from django.db import migrations, models
import django.db.models.deletion
import esite.home.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='button_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='formpage',
            name='registration_button',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.Button'),
        ),
        migrations.AddField(
            model_name='formpage',
            name='registration_head',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formpage',
            name='registration_info_text',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='formpage',
            name='registration_newsletter_text',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formpage',
            name='registration_privacy_text',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='formpage',
            name='registration_step_text',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='button',
            name='button_class',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='button',
            name='button_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='button',
            name='button_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='button',
            name='button_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='thank_you_text',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='uniquepage',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepage',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepage',
            name='copyrightholder',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepage',
            name='court_of_registry',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepage',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepage',
            name='footers',
            field=wagtail.core.fields.StreamField([('f_info', wagtail.core.blocks.StructBlock([('info_placeholder', wagtail.core.blocks.CharBlock(blank=False, classname='full', null=True))], blank=False, icon='placeholder', null=True)), ('code', wagtail.core.blocks.RawHTMLBlock(blank=True, classname='full', icon='code', null=True))], null=True),
        ),
        migrations.AlterField(
            model_name='uniquepage',
            name='headers',
            field=wagtail.core.fields.StreamField([('h_hero', esite.home.models._H_HeroBlock(blank=False, icon='image', null=True)), ('code', wagtail.core.blocks.RawHTMLBlock(blank=True, classname='full', icon='code', null=True))], null=True),
        ),
        migrations.AlterField(
            model_name='uniquepage',
            name='ownership',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepage',
            name='place_of_registry',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepage',
            name='privacy',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='uniquepage',
            name='sections',
            field=wagtail.core.fields.StreamField([('s_why', wagtail.core.blocks.StructBlock([('why_head', wagtail.core.blocks.CharBlock(blank=False, classname='full title', null=True)), ('why_collum1', wagtail.core.blocks.StructBlock([('collum_image', wagtail.images.blocks.ImageChooserBlock(blank=False, null=True)), ('collum_paragraph', wagtail.core.blocks.RichTextBlock(blank=False, classname='full', features=['bold', 'italic', 'underline', 'strikethrough', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'hr', 'embed', 'link', 'document-link', 'image'], null=True))], blank=False, icon='cogs', null=True)), ('why_collum2', wagtail.core.blocks.StructBlock([('collum_image', wagtail.images.blocks.ImageChooserBlock(blank=False, null=True)), ('collum_paragraph', wagtail.core.blocks.RichTextBlock(blank=False, classname='full', features=['bold', 'italic', 'underline', 'strikethrough', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'hr', 'embed', 'link', 'document-link', 'image'], null=True))], blank=False, icon='cogs', null=True)), ('why_collum3', wagtail.core.blocks.StructBlock([('collum_image', wagtail.images.blocks.ImageChooserBlock(blank=False, null=True)), ('collum_paragraph', wagtail.core.blocks.RichTextBlock(blank=False, classname='full', features=['bold', 'italic', 'underline', 'strikethrough', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'hr', 'embed', 'link', 'document-link', 'image'], null=True))], blank=False, icon='cogs', null=True)), ('why_button', wagtail.snippets.blocks.SnippetChooserBlock(esite.home.models.Button))], blank=False, icon='group', null=True)), ('s_individual', wagtail.core.blocks.StructBlock([('individual_head', wagtail.core.blocks.CharBlock(blank=False, classname='full title', null=True)), ('individual_image', wagtail.images.blocks.ImageChooserBlock(blank=False, null=True)), ('individual_lead', wagtail.core.blocks.RichTextBlock(blank=False, classname='full', features=['bold', 'italic', 'underline', 'strikethrough', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'hr', 'embed', 'link', 'document-link', 'image'], null=True)), ('individual_paragraph', wagtail.core.blocks.RichTextBlock(blank=False, classname='full', features=['bold', 'italic', 'underline', 'strikethrough', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'hr', 'embed', 'link', 'document-link', 'image'], null=True)), ('individual_button', wagtail.snippets.blocks.SnippetChooserBlock(esite.home.models.Button))], blank=False, icon='user', null=True)), ('s_experts', wagtail.core.blocks.StructBlock([('experts_head', wagtail.core.blocks.CharBlock(blank=False, classname='full title', null=True)), ('experts_image', wagtail.images.blocks.ImageChooserBlock(blank=False, null=True)), ('experts_lead', wagtail.core.blocks.RichTextBlock(blank=False, classname='full', features=['bold', 'italic', 'underline', 'strikethrough', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'hr', 'embed', 'link', 'document-link', 'image'], null=True)), ('experts_paragraph', wagtail.core.blocks.RichTextBlock(blank=False, classname='full', features=['bold', 'italic', 'underline', 'strikethrough', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'hr', 'embed', 'link', 'document-link', 'image'], null=True)), ('experts_button', wagtail.snippets.blocks.SnippetChooserBlock(esite.home.models.Button))], blank=False, icon='pick', null=True)), ('s_lab', wagtail.core.blocks.StructBlock([('lab_head', wagtail.core.blocks.CharBlock(blank=False, classname='full title', null=True)), ('lab_image', wagtail.images.blocks.ImageChooserBlock(blank=False, null=True)), ('lab_lead', wagtail.core.blocks.RichTextBlock(blank=False, classname='full', features=['bold', 'italic', 'underline', 'strikethrough', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'hr', 'embed', 'link', 'document-link', 'image'], null=True)), ('lab_paragraph', wagtail.core.blocks.RichTextBlock(blank=False, classname='full', features=['bold', 'italic', 'underline', 'strikethrough', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'hr', 'embed', 'link', 'document-link', 'image'], null=True)), ('lab_button', wagtail.snippets.blocks.SnippetChooserBlock(esite.home.models.Button))], blank=False, icon='snippet', null=True)), ('s_method', wagtail.core.blocks.StructBlock([('method_head', wagtail.core.blocks.CharBlock(blank=False, classname='full title', null=True)), ('method_sphere1', wagtail.core.blocks.StructBlock([('sphere_step', wagtail.core.blocks.RichTextBlock(blank=False, classname='full', features=['bold', 'italic', 'underline', 'strikethrough', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'hr', 'embed', 'link', 'document-link', 'image'], null=True))], blank=False, icon='cogs', null=True)), ('method_sphere2', wagtail.core.blocks.StructBlock([('sphere_step', wagtail.core.blocks.RichTextBlock(blank=False, classname='full', features=['bold', 'italic', 'underline', 'strikethrough', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'hr', 'embed', 'link', 'document-link', 'image'], null=True))], blank=False, icon='cogs', null=True)), ('method_sphere3', wagtail.core.blocks.StructBlock([('sphere_step', wagtail.core.blocks.RichTextBlock(blank=False, classname='full', features=['bold', 'italic', 'underline', 'strikethrough', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'hr', 'embed', 'link', 'document-link', 'image'], null=True))], blank=False, icon='cogs', null=True)), ('method_sphere4', wagtail.core.blocks.StructBlock([('sphere_step', wagtail.core.blocks.RichTextBlock(blank=False, classname='full', features=['bold', 'italic', 'underline', 'strikethrough', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'hr', 'embed', 'link', 'document-link', 'image'], null=True))], blank=False, icon='cogs', null=True)), ('method_button', wagtail.snippets.blocks.SnippetChooserBlock(esite.home.models.Button))], blank=False, icon='site', null=True)), ('s_services', wagtail.core.blocks.StructBlock([('services_services', wagtail.core.blocks.StreamBlock([('service', wagtail.core.blocks.StructBlock([('service_head', wagtail.core.blocks.CharBlock()), ('service_content', wagtail.core.blocks.RichTextBlock())], blank=False, icon='doc-full', null=True))], blank=False, null=True)), ('services_button', wagtail.snippets.blocks.SnippetChooserBlock(esite.home.models.Button))], blank=False, icon='openquote', null=True)), ('s_reviews', wagtail.core.blocks.StructBlock([('reviews_head', wagtail.core.blocks.CharBlock(blank=False, classname='full title', null=True)), ('reviews_reviews', wagtail.core.blocks.StreamBlock([('review', wagtail.core.blocks.StructBlock([('review_image', wagtail.images.blocks.ImageChooserBlock(blank=False, null=True)), ('review_quote', wagtail.core.blocks.RichTextBlock(blank=False, classname='full', features=['bold', 'italic', 'underline', 'strikethrough', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'hr', 'embed', 'link', 'document-link', 'image'], null=True)), ('review_name', wagtail.core.blocks.CharBlock(blank=False, classname='full', null=True)), ('review_info', wagtail.core.blocks.CharBlock(blank=False, classname='full', null=True))], blank=False, null=True))], blank=False, null=True))], blank=False, icon='form', null=True)), ('s_pricing', wagtail.core.blocks.StructBlock([('pricing_head', wagtail.core.blocks.CharBlock(blank=False, classname='full title', null=True)), ('pricing_pricingcards', wagtail.core.blocks.StreamBlock([('pricingcard', wagtail.core.blocks.StructBlock([('pricingcard_title', wagtail.core.blocks.CharBlock(blank=False, classname='full title', null=True)), ('pricingcard_description', wagtail.core.blocks.RichTextBlock(blank=False, classname='full', features=['bold', 'italic', 'underline', 'strikethrough', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'hr', 'embed', 'link', 'document-link', 'image'], null=True)), ('pricingcard_price', wagtail.core.blocks.DecimalBlock(blank=False, decimal_places=2, null=True)), ('pricingcard_button', wagtail.snippets.blocks.SnippetChooserBlock(esite.home.models.Button))], blank=False, null=True))], blank=False, max_num=3, null=True))], blank=False, icon='home', null=True)), ('s_about', wagtail.core.blocks.StructBlock([('about_image', wagtail.images.blocks.ImageChooserBlock(blank=False, null=True)), ('about_head', wagtail.core.blocks.CharBlock(blank=False, classname='full title', null=True)), ('about_paragraph', wagtail.core.blocks.RichTextBlock(blank=False, classname='full', features=['bold', 'italic', 'underline', 'strikethrough', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'hr', 'embed', 'link', 'document-link', 'image'], null=True))], blank=False, icon='fa-quote-left', null=True)), ('code', wagtail.core.blocks.RawHTMLBlock(blank=True, classname='full', icon='code', null=True))], null=True),
        ),
        migrations.AlterField(
            model_name='uniquepage',
            name='sociallinks',
            field=wagtail.core.fields.StreamField([('link', wagtail.core.blocks.URLBlock())]),
        ),
        migrations.AlterField(
            model_name='uniquepage',
            name='tax_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepage',
            name='telefax',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepage',
            name='telephone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepage',
            name='token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepage',
            name='trade_register_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepage',
            name='vat_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uniquepage',
            name='zip_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
