# Generated by Django 2.1.3 on 2018-12-05 00:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messdaten',
            fields=[
                ('UID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Temperatur', models.FloatField()),
                ('Luftdruck', models.FloatField()),
                ('Luftfeuchtigkeit', models.FloatField()),
                ('VOC', models.FloatField()),
                ('FEINSTAUBPM25', models.FloatField()),
                ('FEINSTAUBPM100', models.FloatField()),
                ('Datum', models.DateField()),
                ('DatumZeit', models.DateTimeField()),
            ],
        ),
    ]
